-- Vigneshwara Novelties — seed data
--
-- Intentionally empty. Real categories, products, banners and offers are added
-- by the owner through the admin panel (/admin). The schema in 0001_initial.sql
-- creates the tables and RLS policies; you don't need to run this file at all.
--
-- If you ever want a single hero banner for testing the public site, uncomment:
-- insert into public.banners (title, desktop_image_url, mobile_image_url, link_url, position, sort_order)
-- values ('Hero', 'https://your-image-url', 'https://your-mobile-image-url', '/', 'hero', 1);
