import type {
  Banner,
  Category,
  Offer,
  Product,
  ProductImage,
} from "./supabase/types";

// Reliable seeded placeholder images while we wait for the real catalog.
const img = (seed: string, w = 1200, h = 1500) =>
  `https://picsum.photos/seed/vn-${seed}/${w}/${h}`;

const ts = "2025-01-01T00:00:00Z";

const productImage = (
  url: string,
  productId: string,
  isPrimary = false,
  order = 0
): ProductImage => ({
  id: `img-${productId}-${order}`,
  product_id: productId,
  original_url: url,
  optimized_url: url,
  ai_generated_url: null,
  alt_text: null,
  sort_order: order,
  is_primary: isPrimary,
});

export const demoCategories: Category[] = [
  {
    id: "c-1",
    slug: "1gram-gold",
    parent_id: null,
    name_en: "1 Gram Gold",
    name_te: "1 గ్రాము బంగారం",
    description_en: "Lightweight gold-finish jewelry — chains, pendants, earrings & sets.",
    description_te: "తేలికైన బంగారు ఫినిష్ ఆభరణాలు — చైన్‌లు, పెండంట్‌లు, జుంకాలు మరియు సెట్లు.",
    image_url: img("1g-gold", 1200, 1500),
    banner_url: img("1g-gold-banner", 2400, 900),
    sort_order: 1,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-2",
    slug: "german-silver",
    parent_id: null,
    name_en: "German Silver",
    name_te: "జర్మన్ సిల్వర్",
    description_en: "Bracelets, anklets, rings and pooja items in German silver.",
    description_te: "జర్మన్ సిల్వర్‌లో చేతి కడియాలు, పట్టీలు, ఉంగరాలు మరియు పూజ సామాన్లు.",
    image_url: img("german-silver", 1200, 1500),
    banner_url: null,
    sort_order: 2,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-3",
    slug: "pulse-chains",
    parent_id: null,
    name_en: "Pulse Chains",
    name_te: "పల్స్ చైన్‌లు",
    description_en: "Daily-wear pulse chains in many lengths and finishes.",
    description_te: "రోజువారీ ధరించే పల్స్ చైన్‌లు అనేక పొడవులు మరియు ఫినిష్‌లలో.",
    image_url: img("pulse-chain", 1200, 1500),
    banner_url: null,
    sort_order: 3,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-4",
    slug: "gift-articles",
    parent_id: null,
    name_en: "Gift Articles",
    name_te: "బహుమతుల సామాన్లు",
    description_en: "Hand-picked gifts for festivals, weddings and birthdays.",
    description_te: "పండుగలు, వివాహాలు మరియు పుట్టినరోజులకు ఎంపిక చేసిన బహుమతులు.",
    image_url: img("gifts", 1200, 1500),
    banner_url: null,
    sort_order: 4,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-5",
    slug: "watches",
    parent_id: null,
    name_en: "Watches",
    name_te: "గడియారాలు",
    description_en: "Affordable everyday watches.",
    description_te: "రోజువారీ ధరించే అందుబాటు గడియారాలు.",
    image_url: img("watch", 1200, 1500),
    banner_url: null,
    sort_order: 5,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-6",
    slug: "festival-collection",
    parent_id: null,
    name_en: "Festival Collection",
    name_te: "పండుగ కలెక్షన్",
    description_en: "For Sankranti, Ugadi, Diwali, weddings and more.",
    description_te: "సంక్రాంతి, ఉగాది, దీపావళి, వివాహాలు మరియు మరిన్నింటికి.",
    image_url: img("festival", 1200, 1500),
    banner_url: null,
    sort_order: 6,
    is_active: true,
    created_at: ts,
  },
];

const make = (
  id: string,
  data: Omit<Product, "id" | "created_at" | "updated_at" | "images" | "category"> & {
    image: string;
    image2?: string;
  }
): Product => {
  const { image, image2, ...rest } = data;
  return {
    id,
    created_at: ts,
    updated_at: ts,
    ...rest,
    images: [
      productImage(image, id, true, 0),
      ...(image2 ? [productImage(image2, id, false, 1)] : []),
    ],
    category: demoCategories.find((c) => c.id === rest.category_id) ?? null,
  };
};

export const demoProducts: Product[] = [
  make("p-1", {
    slug: "lakshmi-pendant-set",
    sku: "VN-G-001",
    title_en: "Lakshmi Pendant Set (1g Gold)",
    title_te: "లక్ష్మి పెండంట్ సెట్ (1 గ్రాము బంగారం)",
    description_en:
      "Beautiful 1-gram gold pendant set with matching earrings. Lakshmi motif, lightweight, daily-wear friendly.",
    description_te: "అందమైన 1 గ్రాము బంగారు పెండంట్ సెట్, మ్యాచింగ్ జుంకాలతో. లక్ష్మి డిజైన్, తేలిక, రోజువారీ ధరించడానికి అనుకూలం.",
    price_inr: 2200,
    discount_price_inr: 1850,
    category_id: "c-1",
    tags: ["pendant", "set", "lakshmi"],
    stock_status: "in_stock",
    is_featured: true,
    is_trending: true,
    is_new_arrival: false,
    has_sale_badge: true,
    has_offer_badge: false,
    video_url: null,
    sort_order: 1,
    is_active: true,
    image: img("product-1", 1000, 1250),
    image2: img("product-1b", 1000, 1250),
  }),
  make("p-2", {
    slug: "long-haram-1gram",
    sku: "VN-G-002",
    title_en: "Temple Long Haram (1g Gold)",
    title_te: "టెంపుల్ లాంగ్ హారం (1 గ్రాము బంగారం)",
    description_en:
      "Long South Indian style haram in 1-gram gold finish. Perfect for weddings and festivals.",
    description_te: "1 గ్రాము బంగారు ఫినిష్‌లో దక్షిణ భారత శైలి లాంగ్ హారం. వివాహాలు మరియు పండుగలకు అనుకూలం.",
    price_inr: 4500,
    discount_price_inr: null,
    category_id: "c-1",
    tags: ["haram", "wedding", "long"],
    stock_status: "in_stock",
    is_featured: true,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: false,
    has_offer_badge: false,
    video_url: null,
    sort_order: 2,
    is_active: true,
    image: img("product-2", 1000, 1250),
  }),
  make("p-3", {
    slug: "german-silver-anklet",
    sku: "VN-S-001",
    title_en: "German Silver Anklet Pair",
    title_te: "జర్మన్ సిల్వర్ పట్టీలు (జత)",
    description_en: "Pair of German silver anklets with bell charms. Comfortable for daily wear.",
    description_te: "గంట చార్మ్‌లతో జర్మన్ సిల్వర్ పట్టీల జత. రోజువారీ ధరించడానికి సౌకర్యవంతంగా.",
    price_inr: 850,
    discount_price_inr: 720,
    category_id: "c-2",
    tags: ["anklet", "german-silver"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: true,
    is_new_arrival: true,
    has_sale_badge: true,
    has_offer_badge: true,
    video_url: null,
    sort_order: 3,
    is_active: true,
    image: img("product-3", 1000, 1250),
  }),
  make("p-4", {
    slug: "german-silver-pooja-set",
    sku: "VN-S-002",
    title_en: "German Silver Pooja Set (5 piece)",
    title_te: "జర్మన్ సిల్వర్ పూజ సెట్ (5 ముక్కలు)",
    description_en: "Five-piece pooja set in German silver — kalash, lamp, bell, plate and incense holder.",
    description_te: "జర్మన్ సిల్వర్‌లో ఐదు ముక్కల పూజ సెట్ — కలశం, దీపం, గంట, ప్లేట్ మరియు అగరబత్తి స్టాండ్.",
    price_inr: 1850,
    discount_price_inr: null,
    category_id: "c-2",
    tags: ["pooja", "festival", "german-silver"],
    stock_status: "in_stock",
    is_featured: true,
    is_trending: false,
    is_new_arrival: false,
    has_sale_badge: false,
    has_offer_badge: false,
    video_url: null,
    sort_order: 4,
    is_active: true,
    image: img("product-4", 1000, 1250),
  }),
  make("p-5", {
    slug: "pulse-chain-classic",
    sku: "VN-P-001",
    title_en: "Classic Pulse Chain (24 inch)",
    title_te: "క్లాసిక్ పల్స్ చైన్ (24 అంగుళాలు)",
    description_en: "Daily-wear pulse chain, 24-inch length. Light, durable, gold finish.",
    description_te: "రోజువారీ ధరించే పల్స్ చైన్, 24 అంగుళాల పొడవు. తేలిక, మన్నికైన, బంగారు ఫినిష్.",
    price_inr: 950,
    discount_price_inr: 800,
    category_id: "c-3",
    tags: ["pulse-chain", "daily-wear"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: true,
    is_new_arrival: false,
    has_sale_badge: false,
    has_offer_badge: true,
    video_url: null,
    sort_order: 5,
    is_active: true,
    image: img("product-5", 1000, 1250),
  }),
  make("p-6", {
    slug: "gents-everyday-watch",
    sku: "VN-W-001",
    title_en: "Gents Everyday Watch",
    title_te: "పురుషుల రోజువారీ గడియారం",
    description_en: "Comfortable steel-strap watch with simple dial. Easy to read, easy to wear.",
    description_te: "సాధారణ డయల్‌తో సౌకర్యవంతమైన స్టీల్-స్ట్రాప్ గడియారం. చదవడం సులభం, ధరించడం సులభం.",
    price_inr: 1450,
    discount_price_inr: 1200,
    category_id: "c-5",
    tags: ["watch", "gents"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: true,
    has_offer_badge: false,
    video_url: null,
    sort_order: 6,
    is_active: true,
    image: img("product-6", 1000, 1250),
  }),
  make("p-7", {
    slug: "festival-gift-hamper",
    sku: "VN-GF-001",
    title_en: "Festival Gift Hamper",
    title_te: "పండుగ గిఫ్ట్ హాంపర్",
    description_en:
      "A ready-to-gift hamper with German silver pooja items, dry fruits and a small lamp.",
    description_te: "జర్మన్ సిల్వర్ పూజ సామాన్లు, డ్రై ఫ్రూట్స్ మరియు చిన్న దీపంతో రెడీ-టు-గిఫ్ట్ హాంపర్.",
    price_inr: 1750,
    discount_price_inr: null,
    category_id: "c-4",
    tags: ["gift", "festival", "hamper"],
    stock_status: "in_stock",
    is_featured: true,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: false,
    has_offer_badge: false,
    video_url: null,
    sort_order: 7,
    is_active: true,
    image: img("product-7", 1000, 1250),
  }),
  make("p-8", {
    slug: "german-silver-photo-frame",
    sku: "VN-D-001",
    title_en: "German Silver Photo Frame",
    title_te: "జర్మన్ సిల్వర్ ఫోటో ఫ్రేమ్",
    description_en: "8×10 inch photo frame with embossed border. Great wedding & house-warming gift.",
    description_te: "8×10 అంగుళాల ఫోటో ఫ్రేమ్, ఎంబాస్డ్ బోర్డర్‌తో. వివాహం మరియు గృహప్రవేశం కోసం మంచి బహుమతి.",
    price_inr: 650,
    discount_price_inr: 540,
    category_id: "c-4",
    tags: ["frame", "german-silver", "gift"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: true,
    has_offer_badge: false,
    video_url: null,
    sort_order: 8,
    is_active: true,
    image: img("product-8", 1000, 1250),
  }),
];

export const demoOffers: Offer[] = [
  {
    id: "o-1",
    title_en: "Wedding Season Special",
    title_te: "వివాహ సీజన్ స్పెషల్",
    description_en: "Up to 15% off on long harams, sets and pulse chains.",
    description_te: "లాంగ్ హారం, సెట్లు మరియు పల్స్ చైన్‌లపై 15% వరకు ఆఫర్.",
    banner_url: img("offer-wedding", 2000, 800),
    discount_pct: 15,
    starts_at: ts,
    ends_at: "2026-12-31T23:59:59Z",
    is_active: true,
    category_id: null,
  },
  {
    id: "o-2",
    title_en: "Festive Pooja Sale",
    title_te: "పండుగ పూజ సేల్",
    description_en: "10% off on German silver pooja items, this week only.",
    description_te: "జర్మన్ సిల్వర్ పూజ సామాన్లపై 10% ఆఫర్, ఈ వారం మాత్రమే.",
    banner_url: img("offer-pooja", 2000, 800),
    discount_pct: 10,
    starts_at: ts,
    ends_at: "2026-06-30T23:59:59Z",
    is_active: true,
    category_id: null,
  },
];

export const demoBanners: Banner[] = [
  {
    id: "b-1",
    title: "Cherial showroom",
    desktop_image_url: img("hero", 2400, 1200),
    mobile_image_url: img("hero-mobile", 1080, 1440),
    link_url: "/category/1gram-gold",
    position: "hero",
    sort_order: 1,
    is_active: true,
    badge_text: null,
  },
];
