import type {
  Banner,
  Category,
  Offer,
  Product,
  ProductImage,
} from "./supabase/types";

// Reliable seeded placeholder images while we wait for the real catalog.
const img = (seed: string, w = 1200, h = 1500) =>
  `https://picsum.photos/seed/vn-${seed}/${w}/${h}`;

const ts = "2025-01-01T00:00:00Z";

const productImage = (
  url: string,
  productId: string,
  isPrimary = false,
  order = 0
): ProductImage => ({
  id: `img-${productId}-${order}`,
  product_id: productId,
  original_url: url,
  optimized_url: url,
  ai_generated_url: null,
  alt_text: null,
  sort_order: order,
  is_primary: isPrimary,
});

export const demoCategories: Category[] = [
  {
    id: "c-1",
    slug: "jewelry",
    parent_id: null,
    name_en: "Jewelry",
    name_te: "నగలు",
    description_en: "Handpicked heirlooms — gold, silver and precious stones.",
    description_te: "ఎంపిక చేసిన వారసత్వం — బంగారం, వెండి మరియు రత్నాలు.",
    image_url: img("photo-1605100804763-247f67b3557e", 1200, 1500),
    banner_url: img("jewelry-banner", 2400, 900),
    sort_order: 1,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-2",
    slug: "silver",
    parent_id: null,
    name_en: "Silver Articles",
    name_te: "వెండి సామాన్లు",
    description_en: "Pooja sets, idols and dining silver.",
    description_te: "పూజ సెట్లు, విగ్రహాలు మరియు డైనింగ్ వెండి.",
    image_url: img("photo-1610020087147-d9933e8b58a5", 1200, 1500),
    banner_url: null,
    sort_order: 2,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-3",
    slug: "gift-articles",
    parent_id: null,
    name_en: "Gift Articles",
    name_te: "బహుమతుల సామాన్లు",
    description_en: "Curated gifting for festivals and milestones.",
    description_te: "పండుగలు మరియు మైలురాళ్ల కోసం ఎంపిక చేసిన బహుమతులు.",
    image_url: img("photo-1513885535751-8b9238bd345a", 1200, 1500),
    banner_url: null,
    sort_order: 3,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-4",
    slug: "watches",
    parent_id: null,
    name_en: "Watches",
    name_te: "గడియారాలు",
    description_en: "Heritage timepieces.",
    description_te: "వారసత్వ గడియారాలు.",
    image_url: img("photo-1524805444758-089113d48a6d", 1200, 1500),
    banner_url: null,
    sort_order: 4,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-5",
    slug: "decorative",
    parent_id: null,
    name_en: "Decorative",
    name_te: "అలంకరణ",
    description_en: "Pieces that elevate every room.",
    description_te: "ప్రతి గదిని ఎత్తిపట్టే ముక్కలు.",
    image_url: img("photo-1604013898693-d0bf04c80835", 1200, 1500),
    banner_url: null,
    sort_order: 5,
    is_active: true,
    created_at: ts,
  },
  {
    id: "c-6",
    slug: "festival-collection",
    parent_id: null,
    name_en: "Festival Collection",
    name_te: "పండుగ కలెక్షన్",
    description_en: "For Diwali, Sankranti, weddings and beyond.",
    description_te: "దీపావళి, సంక్రాంతి, వివాహాలు మరియు మరిన్నింటికి.",
    image_url: img("photo-1601121141461-9d6647bca1ed", 1200, 1500),
    banner_url: null,
    sort_order: 6,
    is_active: true,
    created_at: ts,
  },
];

const make = (
  id: string,
  data: Omit<Product, "id" | "created_at" | "updated_at" | "images" | "category"> & {
    image: string;
    image2?: string;
  }
): Product => {
  const { image, image2, ...rest } = data;
  return {
    id,
    created_at: ts,
    updated_at: ts,
    ...rest,
    images: [
      productImage(image, id, true, 0),
      ...(image2 ? [productImage(image2, id, false, 1)] : []),
    ],
    category: demoCategories.find((c) => c.id === rest.category_id) ?? null,
  };
};

export const demoProducts: Product[] = [
  make("p-1", {
    slug: "kundan-chandbali",
    sku: "VN-J-001",
    title_en: "Kundan Chandbali Earrings",
    title_te: "కుందన్ చాంద్‌బాలి జుంకాలు",
    description_en:
      "Hand-set kundan chandbali with pearl drops. Crafted by our heritage workshop in Hyderabad.",
    description_te:
      "ముత్యపు చిగుళ్ళతో చేతితో అమర్చిన కుందన్ చాంద్‌బాలి. మా హైదరాబాద్ వారసత్వ వర్క్‌షాప్‌లో రూపొందించబడింది.",
    price_inr: 18500,
    discount_price_inr: 15900,
    category_id: "c-1",
    tags: ["earrings", "kundan", "bridal"],
    stock_status: "in_stock",
    is_featured: true,
    is_trending: true,
    is_new_arrival: false,
    has_sale_badge: true,
    has_offer_badge: false,
    video_url: null,
    sort_order: 1,
    is_active: true,
    image: img("photo-1535632787350-4e68ef0ac584", 1000, 1250),
    image2: img("photo-1611591437281-460bfbe1220a", 1000, 1250),
  }),
  make("p-2", {
    slug: "temple-haram",
    sku: "VN-J-002",
    title_en: "Temple Haram Necklace",
    title_te: "టెంపుల్ హారం",
    description_en:
      "South Indian temple haram in 22k gold. Ruby and emerald motifs of Lakshmi.",
    description_te: "22 క్యారెట్ బంగారంలో దక్షిణ భారత టెంపుల్ హారం. లక్ష్మి యొక్క కెంపు మరియు పచ్చ మోటిఫ్‌లు.",
    price_inr: 142000,
    discount_price_inr: null,
    category_id: "c-1",
    tags: ["necklace", "temple", "wedding"],
    stock_status: "made_to_order",
    is_featured: true,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: false,
    has_offer_badge: false,
    video_url: null,
    sort_order: 2,
    is_active: true,
    image: img("photo-1599643477877-530eb83abc8e", 1000, 1250),
  }),
  make("p-3", {
    slug: "silver-pooja-set",
    sku: "VN-S-001",
    title_en: "Heritage Silver Pooja Set",
    title_te: "వారసత్వ వెండి పూజ సెట్",
    description_en:
      "Five-piece pooja set in 925 silver — kalash, lamp, bell, plate and incense holder.",
    description_te: "925 వెండిలో ఐదు ముక్కల పూజ సెట్ — కలశం, దీపం, గంట, ప్లేట్ మరియు అగరబత్తి స్టాండ్.",
    price_inr: 24500,
    discount_price_inr: 21900,
    category_id: "c-2",
    tags: ["pooja", "silver", "festival"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: true,
    is_new_arrival: true,
    has_sale_badge: true,
    has_offer_badge: true,
    video_url: null,
    sort_order: 3,
    is_active: true,
    image: img("photo-1606293459251-fae7e8366b32", 1000, 1250),
  }),
  make("p-4", {
    slug: "lakshmi-idol",
    sku: "VN-S-002",
    title_en: "Lakshmi Silver Idol",
    title_te: "లక్ష్మి వెండి విగ్రహం",
    description_en: "Hand-cast 4-inch Lakshmi idol in 925 silver. Seated on lotus pedestal.",
    description_te: "925 వెండిలో చేతితో పోసిన 4-అంగుళాల లక్ష్మి విగ్రహం. తామర పీఠంపై కూర్చున్నది.",
    price_inr: 18900,
    discount_price_inr: null,
    category_id: "c-2",
    tags: ["idol", "silver", "lakshmi"],
    stock_status: "in_stock",
    is_featured: true,
    is_trending: false,
    is_new_arrival: false,
    has_sale_badge: false,
    has_offer_badge: false,
    video_url: null,
    sort_order: 4,
    is_active: true,
    image: img("photo-1610375229774-9c8d7416da81", 1000, 1250),
  }),
  make("p-5", {
    slug: "gold-bangles-pair",
    sku: "VN-J-003",
    title_en: "Antique Gold Bangle Pair",
    title_te: "పురాతన బంగారు గాజుల జత",
    description_en: "22k gold bangles with antique finish. Engraved temple motifs.",
    description_te: "పురాతన ముగింపుతో 22 క్యారెట్ బంగారు గాజులు. చెక్కబడిన టెంపుల్ మోటిఫ్‌లు.",
    price_inr: 86500,
    discount_price_inr: 82000,
    category_id: "c-1",
    tags: ["bangles", "gold", "antique"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: true,
    is_new_arrival: false,
    has_sale_badge: false,
    has_offer_badge: true,
    video_url: null,
    sort_order: 5,
    is_active: true,
    image: img("photo-1602173574767-37ac01994b2a", 1000, 1250),
  }),
  make("p-6", {
    slug: "engraved-mens-watch",
    sku: "VN-W-001",
    title_en: "Heritage Engraved Watch",
    title_te: "వారసత్వ చెక్కిన గడియారం",
    description_en: "Stainless steel automatic with engraved bezel. 5-year guarantee.",
    description_te: "చెక్కిన బెజల్‌తో స్టెయిన్‌లెస్ స్టీల్ ఆటోమేటిక్. 5-సంవత్సరాల హామీ.",
    price_inr: 7500,
    discount_price_inr: 6200,
    category_id: "c-4",
    tags: ["watch", "men", "engraved"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: true,
    has_offer_badge: false,
    video_url: null,
    sort_order: 6,
    is_active: true,
    image: img("photo-1524805444758-089113d48a6d", 1000, 1250),
  }),
  make("p-7", {
    slug: "wedding-gift-hamper",
    sku: "VN-G-001",
    title_en: "Curated Wedding Gift Hamper",
    title_te: "ఎంపిక చేసిన వివాహ బహుమతుల సెట్",
    description_en:
      "A signature box of silver gifts, sweets and dry fruits — wrapped in handloom cloth.",
    description_te: "వెండి బహుమతులు, స్వీట్లు మరియు డ్రై ఫ్రూట్స్‌తో కూడిన ప్రత్యేక బాక్స్ — హ్యాండ్‌లూమ్ వస్త్రంలో చుట్టబడింది.",
    price_inr: 12500,
    discount_price_inr: null,
    category_id: "c-3",
    tags: ["gift", "wedding", "hamper"],
    stock_status: "in_stock",
    is_featured: true,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: false,
    has_offer_badge: false,
    video_url: null,
    sort_order: 7,
    is_active: true,
    image: img("photo-1513885535751-8b9238bd345a", 1000, 1250),
  }),
  make("p-8", {
    slug: "silver-photo-frame",
    sku: "VN-D-001",
    title_en: "Embossed Silver Photo Frame",
    title_te: "ఎంబాస్డ్ వెండి ఫోటో ఫ్రేమ్",
    description_en: "8x10 inch silver-plated frame with embossed paisley border.",
    description_te: "8x10 అంగుళాల వెండి-పూతతో కూడిన ఫ్రేమ్, ఎంబాస్డ్ పైస్లీ బోర్డర్‌తో.",
    price_inr: 4500,
    discount_price_inr: 3800,
    category_id: "c-5",
    tags: ["frame", "silver", "decor"],
    stock_status: "in_stock",
    is_featured: false,
    is_trending: false,
    is_new_arrival: true,
    has_sale_badge: true,
    has_offer_badge: false,
    video_url: null,
    sort_order: 8,
    is_active: true,
    image: img("photo-1582719471384-894fbb16e074", 1000, 1250),
  }),
];

export const demoOffers: Offer[] = [
  {
    id: "o-1",
    title_en: "Wedding Season Atelier",
    title_te: "వివాహ సీజన్ ఆట్లియర్",
    description_en: "Up to 15% off on bridal jewelry, made-to-order included.",
    description_te: "వధువు నగలపై 15% వరకు ఆఫర్, ఆర్డర్‌పై తయారుచేసేవి కూడా.",
    banner_url: img("photo-1611591437281-460bfbe1220a", 2000, 800),
    discount_pct: 15,
    starts_at: ts,
    ends_at: "2026-12-31T23:59:59Z",
    is_active: true,
  },
  {
    id: "o-2",
    title_en: "Festive Silver Sale",
    title_te: "పండుగ వెండి అమ్మకం",
    description_en: "10% off on pooja sets and idols, this week only.",
    description_te: "పూజ సెట్లు మరియు విగ్రహాలపై 10% ఆఫర్, ఈ వారం మాత్రమే.",
    banner_url: img("photo-1601121141461-9d6647bca1ed", 2000, 800),
    discount_pct: 10,
    starts_at: ts,
    ends_at: "2026-06-30T23:59:59Z",
    is_active: true,
  },
];

export const demoBanners: Banner[] = [
  {
    id: "b-1",
    title: "Heirlooms collection",
    desktop_image_url: img("photo-1620562437536-de08e0b6f2e2", 2400, 1200),
    mobile_image_url: img("photo-1620562437536-de08e0b6f2e2", 1080, 1440),
    link_url: "/category/jewelry",
    position: "hero",
    sort_order: 1,
    is_active: true,
  },
];
